### ISSUE TITLE
Make Common Components

### ISSUE THREAD

**Issue by 05Castle** [Moya-news/Moya_for_desktop#4]
# Description
모든 페이지에 공통적으로 들어가는 컴포넌트 작성.
내비게이션(사이드바), 헤더(검색창)

# Tasks
내비게이션
- [x] 컴포넌트 작성 및 스타일링
- [x] 라우터 링크 연결
- [x] 현재 활성화된 메뉴 표시
- [x] 활성화된 메뉴 아이콘도 테마 컬러로 색변경 되며 강조 표시

헤더
- [x] 컴포넌트 작성 
- [x] 컴포넌트 스타일링
- [x] 검색 기능
- [x] 검색 리스트 필터링
- [x] 검색 결과 sort 기준 정하고 적용하기 (해외의 경우, 검색어에 해당되는 심볼 → 기업이름 순서로 오름차순 리스트업) 
- [x] 검색창 외부 클릭 시 포커스 아웃 기능 (utils 경로에 놓고 재활용)
- [x] 엔터 이벤트 추가 (검색 결과의 첫번째 검색 리스트로 이동하도록)
- [x] 최근 검색 기록

주식 개요표(서브 헤더)
- [x] 컴포넌트 작성
- [x] 스타일링
- [x] 페이지에 따라서 표시/비표시 변경(검색전에는 표시 최근 검색 목록이 표시)
- [x] 기업 설명칸 토글

레이아웃
- [x] 공통되는 컴포넌트 묶어서 레이아웃으로 통합
- [x] 레이아웃 라우터 적용
- [x] 반응형 디자인 적용

# ETC
고정되어 있는 기초적인 레이아웃 적용 완료.
디자인  시안, 라우터 페이지 연결 등의 진행 상황에 맞춰서 추가적인 작업이 필요함.

- [x] 내비게이션 아이콘 디자인이 변경되었음.  이미지 파일 변경 필요.    
- [x] 국내 종목 검색시 영어 대/소문자 구분이 안되고 있음.  한글은 toLowerCase 메서드가 오류를 발생함.  한글과 영어 두가지를 모두 인식하는 검색창으로 업그레이드 필요. → **단순한 에러였던 것 같음.  지금은 멀쩡히 toLowerCase가 적용됨.**
- [x] 로고 이미지가 가끔씩 안 보여지는 오류.  이미지 불러오는 방법을 바꿀 필요.

**Comment by GyoHeonLee** [comment]
향후 반응형 디자인 채택시 추가 작업 실시
