### ISSUE TITLE
Make domestic stock main page

### ISSUE THREAD

**Issue by juhan00** [Moya-news/Moya_for_desktop#9]
# Description
주식 검색 전 화면 페이지 컴포넌트 제작.
코스피/코스닥/코스피 200지수, TOP종목, 인기검색 종목, 코스닥 인기검색 종목, 최근 본 종목, 관심종목

# Tasks
- [ ] 데이터 가져오기
- [ ] TOP종목, 인기검색 종목, 코스닥 인기검색 종목 UI 제작
- [ ] 코스피/코스닥/코스피 200지수 UI 제작
- [ ] 최근 본 종목, 관심종목 UI 제작

# ETC
기타 사항
